Add methodology docs, close #17
EduWebDotNet/methodology pull request #23
Opened 2024-03-22 19:30 UTC by nealcrafter

Add methodology docs, close #17

2024-03-24 19:09 UTC, kulakovt requested changes

2024-03-24 19:09 UTC, kulakovt commented on wiki/Task rules.md
> +Вопросы по реализации необходимо задавать в комментариях к задаче, но также можно обсуждать в чате Методологов, в личном чате с автором задачи, на встречах, при этом результаты обсуждения правильнее
В личном чате я бы не стал советовать. Ибо могут потеряться. И результаты обсуждения **обязательно** перенести потом в задачу.

2024-03-24 19:09 UTC, kulakovt commented on wiki/Task rules.md
> +Промежуточный статус решения задачи необходимо отражать в комментариях к задаче, также сообщать в чате методологов два раза в неделю.
Мне кажется. что в задаче не нужно отражать прогресс. Это лишь загрязнит основной текст. Лучше только в чате, во вторник и в пятницу.

2024-03-24 19:09 UTC, kulakovt commented on wiki/Task rules.md
> +После выполнения задачи, убедившись что задача полностью реализована, необходим отправить ее на проверку автору. Для отправки на проверку необходимо сделать PR, написать комментарий в задаче, автор п
Можно добавить что все изменения в wiki делаются только через PR в основной репозиторий. После мёржа они попадут в wiki.

2024-03-24 19:09 UTC, kulakovt commented on wiki/Task rules.md
> +Если исполнитель не может продолжить работу над задачей, то он освобождает ее, сообщает об этом в комментариях к задаче и в чате Методологов. Если по задаче достигнуты какие-то результаты, по возможн
Можно только в чате, чтобы не пачкать текст задачи

2024-03-24 19:09 UTC, kulakovt commented on wiki/Task rules.md
> +Если в течении двух недель от исполнителя не поступает информации о результатах работы над задачей, то автор задачи или иное ответственное лицо снимает задачу с исполнителя.
Если человек уезжает в отпуск, то можно предупредить заранее в чате, когда планируется вернуться к работе.

2024-03-25 16:46 UTC, nealcrafter reviewed
Учтены комментарии при PR

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +### Как закрепить выбранную задачу за собой
```suggestion
### Как закрепить выбранную задачу за собой
Первым абзацем в задаче может быть тема «Зависит от:» со списком ссылок на задачи, которые необходимо закрыть до того как эту задачу начинать делать. Это нужно учитывать перед тем как преступать к работе над задачей.
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +![изображение](https://github.com/EduWebDotNet/methodology/assets/129661284/0da20694-9da2-456d-8df7-44bde0a2c7fa)
```suggestion
Для закрепления выбранной задачи, необходимо упомянать @kulakovt с номером задачи и GH-ником в телеграм-группе методологов EduDotNet.Meth, после этого ожидать назначения задачи.
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +Если у вас нет прав назначать себя исполнителем, необходимо написать в комментариях к задаче о необходимости назначить вас исполнителем.
```suggestion
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +### Как закрепить выбранную задачу за собой
Скорректировал

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +![изображение](https://github.com/EduWebDotNet/methodology/assets/129661284/0da20694-9da2-456d-8df7-44bde0a2c7fa)
Скорректировал

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +Если у вас нет прав назначать себя исполнителем, необходимо написать в комментариях к задаче о необходимости назначить вас исполнителем.
Удалил пункт,  т.к. выше учтено.

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +> TODO: подумать над тем нужно ли при принятии в работу или чуть позже указывать плановую дату решения, и как указывать.
```suggestion
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +Вопросы по реализации необходимо задавать в комментариях к задаче, но также можно обсуждать в чате Методологов, в личном чате с автором задачи, на встречах, при этом результаты обсуждения правильнее
```suggestion
Вопросы по реализации необходимо задавать в комментариях к задаче, но также можно обсуждать в чате Методологов, на встречах, при этом результаты обсуждения обязательно перенести в комментарии к задаче.
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +Промежуточный статус решения задачи необходимо отражать в комментариях к задаче, также сообщать в чате методологов два раза в неделю.
```suggestion
Промежуточный статус решения задачи необходимо сообщать в чате методологов два раза в неделю, во вторник и в пятницу.
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +Если исполнитель не может продолжить работу над задачей, то он освобождает ее, сообщает об этом в комментариях к задаче и в чате Методологов. Если по задаче достигнуты какие-то результаты, по возможн
```suggestion
Если исполнитель не может продолжить работу над задачей, то он освобождает ее, сообщает об этом в чате Методологов. Если по задаче достигнуты какие-то результаты, по возможности предлагает участникам в чате взять данную задачу и передать наработки.
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +Если в течении двух недель от исполнителя не поступает информации о результатах работы над задачей, то автор задачи или иное ответственное лицо снимает задачу с исполнителя.
```suggestion
Если в течении двух недель от исполнителя не поступает информации о результатах работы над задачей, то автор задачи или иное ответственное лицо снимает задачу с исполнителя.
В отдельных случаях (например, период отпуска), можно предупредить заранее в чате Методологов, когда планируется вернуться к работе над задачей.
```

2024-03-25 16:46 UTC, nealcrafter commented on wiki/Task rules.md
> +После выполнения задачи, убедившись что задача полностью реализована, необходим отправить ее на проверку автору. Для отправки на проверку необходимо сделать PR, написать комментарий в задаче, автор п
```suggestion
После выполнения задачи, убедившись что задача полностью реализована, необходим отправить ее на проверку автору. Для отправки на проверку необходимо сделать PR, написать комментарий в задаче, автор получит оповещение, в случае если замечаний нет, напишет об этом в ответных комментариях.
Все изменения в wiki делаются только через PR в основной репозиторий в папке "wiki", после мёржа они попадут в wiki.
```

2024-03-25 16:55 UTC, nealcrafter reviewed
Скорректировал

2024-03-25 20:15 UTC, kulakovt commented on wiki/Task rules.md
> +Открыть список задач можно перейдя на главной странице репозитория выбрав в соответствующий пункт Issues меню, расположенного под названием репозитория, прямая ссылка на список задач https://github.c
```suggestion
Открыть список задач можно перейдя на главной странице репозитория выбрав в соответствующий пункт Issues меню, расположенного под названием репозитория, прямая ссылка на [список задач](https://github.com/EduWebDotNet/methodology/issues).
```

2024-03-25 20:15 UTC, kulakovt approved these changes

2024-03-25 20:16 UTC, merged