Taskrules 20240326 (исправление)
EduWebDotNet/methodology pull request #24
Opened 2024-03-26 16:53 UTC by nealcrafter

Не зафиксированы изменения при PR

2024-03-29 18:11 UTC, kulakovt requested changes

2024-03-29 18:11 UTC, kulakovt commented on wiki/Task rules.md
>  > TODO:
Файлы для wiki правильнее называть в Kebab-case (`Task-rules` или `Issue-rules`). Т.е. заменить все пробелы на знак минус («-»). Именно так формируются url сегменты в wiki страничках. А ссылаться на них можно так же через пробел.

2024-03-31 16:32 UTC, nealcrafter commented on wiki/Task rules.md
>  > TODO:
Изменил имя файла на Issue-rules

2024-03-31 19:05 UTC, kulakovt approved these changes

2024-03-31 19:06 UTC, merged